
FactoryBot.define do
  factory :milestone do
    child
    note
    sequence(:question) { Milestone::QUESTIONS.sample }
    sequence(:answer) { Milestone::ANSWERS.sample }
    autogenerated_note { "#{child.name} has made this for the first time" }
  end
end
