require 'rails_helper'
require 'pry'

RSpec.describe Milestone, type: :model do
  describe 'validations' do
    subject { FactoryBot.create(:milestone) }
    it { is_expected.to validate_presence_of(:note_id) }
    it { is_expected.to validate_presence_of(:child_id) }
    it { is_expected.to validate_presence_of(:question) }
    it { is_expected.to validate_presence_of(:answer) }
    it { is_expected.to validate_presence_of(:autogenerated_note) }
  end

  context 'it has note_id, child_id' do
    before(:each) do
      @child = FactoryBot.create(:child)
      @note = FactoryBot.create(:note, note_body: 'my lovely baby, note number 1', child: @child)
    end
    after(:each) do
      @child.destroy
      @note.destroy
    end

    it 'is has note_id' do
      @milestone = FactoryBot.create(:milestone, child: @child, note: @note)
      expect(@milestone.note_id).to eq(@note.id)
    end

    it 'has a child_id' do
      @milestone = FactoryBot.create(:milestone, child: @child, note: @note)
      expect(@milestone.child_id).to eq(@child.id)
    end
  end


end
