# frozen_string_literal: true

class CreateMilestones < ActiveRecord::Migration[6.1]
  def change
    create_table :milestones do |t|
      t.integer :note_id, null: false
      t.integer :child_id, null: false
      t.string :question, null: false
      t.string :answer, null: false
      t.string :autogenerated_note, null: false

      t.timestamps
    end
  end
end
