# frozen_string_literal: true

class Milestone < ApplicationRecord
  QUESTIONS = [
     "Did your baby have a first bath this week?",
     "Did your baby smile at you for the first time this week?",
     "Did your baby rollover for the first time this week?"
     "Did your baby hold head up for the first time this week?",
     "Did your baby get a new tooth this week?",
     "Did your baby hold on to a toy for the first time this week?",
     "Did your baby try new food for the first time this week?",
     "Did your baby crawl for the first time this week?",
     "Did your baby laugh for the first time this week?",
     "Did your baby sleep through the night this week?",
     "Did your baby sat up for the first time this week?",
     "Did your baby crawl for the first time this week?",
     "Did your baby say a first word this week?",
     "Did your baby wave bye-bye for the first time this week?",
     "Did your baby eat herself for the fist time this week?",
     "Did your baby stand up for the first time this week?",
     "Did your child did a first step this week?",
     "Did your child stack one bloc on the top of another for the first time this week?"
  ]
  ANSWERS = %w[yes, not yet, almost]
  belongs_to :child
  validates :child_id, presence: true
  validates :note_id, presence: true
  validates :question, presence: true, inclusion: { in: QUESTIONS }
  validates :answer, presence: true, inclusion: { in: ANSWERS }
  validates :autogenerated_note, presence: true 
end
